### ISSUE TITLE
WARN: Fixed frame not set

### ISSUE THREAD

**Issue by juanvon** [leggedrobotics/art_planner#14]
I'm currently running into this problem, when I give goal pose in the terminal. It gets stuck unless I manually turn it off. The image is below
![图片1](https://github.com/leggedrobotics/art_planner/assets/87421767/0cb0421b-987a-402a-9d93-2900334f7ce5)
And there is a "Fixed frame not set." WARN at the same time. I set a loginfo in `updateCurrentPose` to show the fixed_frame. However, it seems to be 'None'.
I can't solve this problem by now.
I use 'elevation mapping cupy' package to generate an elevation map, and I use 16 lines lidar to collect pointcloud. Here are the pictures.
![图片2](https://github.com/leggedrobotics/art_planner/assets/87421767/fe7b6bac-5003-4814-a662-b860031fe871)
![图片4](https://github.com/leggedrobotics/art_planner/assets/87421767/729b43e6-7967-461a-a6ec-d6c3bce057bb)
![图片5](https://github.com/leggedrobotics/art_planner/assets/87421767/604c3d84-4e9f-4803-867d-77357cfa5c7b)

**Comment by lorenwel** [comment]
Hi, 
the terminal shows various warnings related to missing map information. 
Do you have elevation mapping running and are the topic names correctly set?
Please make sure that the `~elevation_map` topic in the `art_planner_ros/launch/art_planner.launch` file is set to your map topic.

**Comment by juanvon** [comment]
Yes. I have elevation mapping running and the topic are correctly set.
![Snipaste_2023-08-22_19-13-02](https://github.com/leggedrobotics/art_planner/assets/87421767/46f39a4f-74b1-46d9-a5c7-7de25ac1f2da)
![Snipaste_2023-08-22_19-08-10](https://github.com/leggedrobotics/art_planner/assets/87421767/4639ac97-fae3-486d-b005-f000a4ce68e7)
![Snipaste_2023-08-22_19-07-57](https://github.com/leggedrobotics/art_planner/assets/87421767/4d28ea17-52ae-4536-98d1-874c471093fa)

**Comment by juanvon** [comment]
but the problem still remain

**Comment by lorenwel** [comment]
Ok. The warning about no fixed frame is from the path follower, which basically just means that it didn't receive a path, yet. So that's not the underlying issue.

I need a bit more detailed description. After your first screenshot, is there any more output in the terminal? Are there any more warnings or errors? 
Because the cost computation service is being called, so I do not know where the planner should get stuck.

**Comment by juanvon** [comment]
Here are more detailed description. I give a goal pose and the planner seems to get it. It starts after several "Got query of length xx". Then the terminal shows a lot of "Got query of length 1" and the legged robot walk around the goal pose until it get stuck by itself and fall down.
I read all the issue and set the parameter according to them like  `feet/offset/z` `unknown_space_untraversable`. The current situation is the best I can do so far.

![Snipaste_2023-08-23_19-48-44](https://github.com/leggedrobotics/art_planner/assets/87421767/e58f3a1c-16b2-4ed9-81ff-cb0710be3f36)
![Snipaste_2023-08-23_19-48-59](https://github.com/leggedrobotics/art_planner/assets/87421767/88acbb4e-c78b-4424-9ed7-98bb8c72cb40)
![Snipaste_2023-08-23_19-49-08](https://github.com/leggedrobotics/art_planner/assets/87421767/75308a24-c185-44af-b531-0d2f63737f1e)
![Snipaste_2023-08-23_19-49-20](https://github.com/leggedrobotics/art_planner/assets/87421767/d318af31-671d-426b-93b1-6abdb332865b)
![Snipaste_2023-08-23_19-49-47](https://github.com/leggedrobotics/art_planner/assets/87421767/d31db6cf-e883-4d9e-a23c-55fcee109804)

**Comment by lorenwel** [comment]
Thanks for all the info. 
So then I do not quite understand what the problem is, since the planner publishes a path and the robot is moving. 
How does the robot get stuck? Does it not properly follow the path? Is there a obstacle that is being planned over but the robot cannot overcome?

The final error you see with no valid initial states is probably a symptom of the robot getting stuck or falling over. In that case the robot pose is not valid as a starting node anymore and the planner cannot work.

**Comment by lorenwel** [comment]
Please re-open if this issue is still current.

**Comment by nanbwrn** [comment]
I started the planner and set a 2D Nav Goal, but the robot didn't take any actions in the simulation. When you control a robot, what are your steps? I first started the robot's control program, which can receive velocity control topics, and then I started the planner program. Both the elevation map and velocity topics are being published, but the robot doesn't move, likely because it hasn't received the path from the planner. I used the echo command and didn't see any path information. Additionally, the terminal showed the warning 'Fixed frame not set.' How do you solve this problem?
I really appreciate your reply.This issue has been bothering me for a long time.

![d46e56ea60d1b14803089aa5b9fd3bc](https://github.com/user-attachments/assets/57628f5b-e88b-4702-87d2-cb8dc755b969)

**Comment by lorenwel** [comment]
> I started the planner and set a 2D Nav Goal, but the robot didn't take any actions in the simulation. When you control a robot, what are your steps? I first started the robot's control program, which can receive velocity control topics, and then I started the planner program. Both the elevation map and velocity topics are being published, but the robot doesn't move, likely because it hasn't received the path from the planner. I used the echo command and didn't see any path information. Additionally, the terminal showed the warning 'Fixed frame not set.' How do you solve this problem? I really appreciate your reply.This issue has been bothering me for a long time.
> 
> ![d46e56ea60d1b14803089aa5b9fd3bc](https://private-user-images.githubusercontent.com/132453617/351164688-57628f5b-e88b-4702-87d2-cb8dc755b969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjU1NTEsIm5iZiI6MTcyMTcyNTI1MSwicGF0aCI6Ii8xMzI0NTM2MTcvMzUxMTY0Njg4LTU3NjI4ZjViLWU4OGItNDcwMi04N2QyLWNiOGRjNzU1Yjk2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwOTAwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjM1NTVkOTZmZWE2YjFlYTVhN2RkYWEwZWJmNzdlOTYyYzI1ZmY2ZDQwNWJkYmNmNzEzYTM2OTUxMWY5ZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FeaJCzw5Y7Kfqqar8MbMVddOrWBWavOC9bcx7BoIGX4)

Did you send a goal to the planner?
The terminal on the left side does not show that any goal was received.
Make sure you send a goal to the correct topic.

**Comment by nanbwrn** [comment]
hi,@lorenwel 
Thank you for your reply. I apologize for the late response. I have now modified the topic that the planner receives, published the goal point, and successfully received it. However, I have encountered a new problem and have opened a new issue.

**Comment by akkoyunlu** [comment]
> hi,[@lorenwel](https://github.com/lorenwel) Thank you for your reply. I apologize for the late response. I have now modified the topic that the planner receives, published the goal point, and successfully received it. However, I have encountered a new problem and have opened a new issue.

How did you solve problems you encountered? Could you show param.yaml ?
