### ISSUE TITLE
How to plan foothold？

### ISSUE THREAD

**Issue by xin111222** [leggedrobotics/art_planner#15]
hello，I have a confusion, how do you control the foothold only by controlling cmd_vel?

**Comment by lorenwel** [comment]
Hi, 
there must be a misunderstanding. This planner does not perform explicit foothold planning. It rather makes sure that for every planned base position there would be something.
In addition, the cmd_vel output is only published by the path follower. This is simply a convenience tool to follow a published path, since velocities are the most common interface to legged robots.
