### ISSUE TITLE
Minimum working demo

### ISSUE THREAD

**Issue by justinberi** [leggedrobotics/art_planner#5]
Hi, I am looking for a minimum working demonstration with visualisation. 

Your readme states 

> We provide a launch file which should be everything you need, if you work with ANYmal.

and 

> You can use the 2D Nav Goal in RViz to set a goal pose for the planner.

which suggests there is an external ANYmal simulator/ros package that this compatible with. But I am unfamiliar with that. 

Are you able to provide guidance on how to run this with that simulator if it exists?

**Comment by lorenwel** [comment]
Hi @justinberi 
sorry for the glacial response time. Unforunately, I cannot provide a working demo, since it would require access to [ANYmal Research](https://www.anymal-research.org/) to do that reasonably. 
However, it shouldn't be too hard to get everything up-and-running on your own robot, if you have it running in Gazebo or real-life. You will only have to adjust the `robot` parameters in the `art_planner_ros/config/params.yaml` file to the specifications of your robot. 
Of course you will also need some sort of height mapping as input to the planner (e.g. [elevation_mapping_cupy](https://github.com/leggedrobotics/elevation_mapping_cupy) ).

If you manage to create a launch file and instructions for running it with some default Gazebo robots, I'd be happy to include it with a PR>
